version: '3'

services:
    database:
      image: mongo:4.2.0
      container_name: my_best_pal_container
      environment:
        - MONGO_INITDB_DATABASE=mybestpal
      ports:
        - 27017:27017
      volumes:
        - mongodb:/data/db

volumes:
  mongodb: